services:
  app:
    build: .
    container_name: server-monitor-be
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    container_name: server-monitor-nginx
    restart: always
    ports:
      - "80:80"
      #- "443:443" # Uncomment after SSL setup
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      #- ./certbot/conf:/etc/letsencrypt # For SSL
      #- ./certbot/www:/var/www/certbot # For SSL
    depends_on:
      - app
