export enum CommandType {
    RESTART_SERVICE = 'RESTART_SERVICE',
    SHELL_CMD = 'SHELL_CMD',
    UPDATE_AGENT = 'UPDATE_AGENT',
    KILL_PROCESS = 'KILL_PROCESS',
    GET_ACTIVE_USERS = 'GET_ACTIVE_USERS',
}
